### ISSUE TITLE
Error: `SyntaxError: Unexpected end of JSON input` should not cause step to fail

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle-build-action#119]
```
0s
Post job cleanup.
Error: SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.assign [as rehydrate] (/home/runner/work/_actions/gradle/gradle-build-action/v2.0.0/dist/src/cache-base.ts:77:1)
    at Object.<anonymous> (/home/runner/work/_actions/gradle/gradle-build-action/v2.0.0/dist/src/caches.ts:63:1)
    at Generator.next (<anonymous>)
    at rejected (/home/runner/work/_actions/gradle/gradle-build-action/v2.0.0/dist/src/caches.ts:26:32)
    at new Promise (<anonymous>)
    at P (/home/runner/work/_actions/gradle/gradle-build-action/v2.0.0/dist/src/caches.ts:22:28)
    at Object.restore [as save] (/home/runner/work/_actions/gradle/gradle-build-action/v2.0.0/dist/src/caches.ts:61:8)
    at /home/runner/work/_actions/gradle/gradle-build-action/v2.0.0/dist/src/post.ts:35:1
    at Generator.next (<anonymous>)
```

https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/runs/4200743868?check_suite_focus=true

**Comment by JavierSegoviaCordoba** [comment]
Personally I would prefer the action to delete all the cache or just avoid crashing in the post step, because I have other jobs later that are not being launch but they could if post step was not crashing, and they aren't related to Gradle so losing this cache is not a problem for them.

**Comment by bigdaz** [comment]
@JavierSegoviaCordoba Yes, the goal is for failures in caching to be reported as warnings and for the Job to continue. Clearly there are some edge cases I missed. Thanks for reporting: I'll investigate.

**Comment by bigdaz** [comment]
`v2.0.1` has been released, which contains a fix for this issue
