### ISSUE TITLE
node16 is suddenly not supported anymore?

### ISSUE THREAD

**Issue by peterfigure** [gradle/gradle-build-action#176]
```
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load gradle/gradle-build-action/v2/action.yml
```

**Comment by peterfigure** [comment]
i believe this was caused in a regression in runner versions in our self hosted runners
