### ISSUE TITLE
TypeError: Input does not meet YAML 1.2

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle-build-action#316]
```
Warning: Unhandled error in Gradle post-action - job will continue: TypeError: Input does not meet YAML 1.2 "Core Schema" specification: cache-read-only
[8](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:8)
Support boolean input list: `true | True | TRUE | false | False | FALSE`
[9](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:9)
TypeError: Input does not meet YAML 1.2 "Core Schema" specification: cache-read-only
[10](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:10)
Support boolean input list: `true | True | TRUE | false | False | FALSE`
[11](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:11)
    at Object.getBooleanInput (/home/runner/work/_actions/Wandalen/gradle-build-action/dist/webpack:/gradle-build-action/node_modules/@actions/core/lib/core.js:151:1)
[12](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:12)
    at isCacheReadOnly (/home/runner/work/_actions/Wandalen/gradle-build-action/dist/webpack:/gradle-build-action/src/cache-utils.ts:60:1)
[13](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:13)
    at Object.<anonymous> (/home/runner/work/_actions/Wandalen/gradle-build-action/dist/webpack:/gradle-build-action/src/caches.ts:77:1)
[14](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:14)
    at Generator.next (<anonymous>)
[15](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:15)
    at /home/runner/work/_actions/Wandalen/gradle-build-action/dist/webpack:/gradle-build-action/src/caches.ts:31:1
[16](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:16)
    at new Promise (<anonymous>)
[17](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:17)
    at __webpack_modules__.3800.__awaiter (/home/runner/work/_actions/Wandalen/gradle-build-action/dist/webpack:/gradle-build-action/src/caches.ts:27:1)
[18](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:18)
    at Object.save (/home/runner/work/_actions/Wandalen/gradle-build-action/dist/webpack:/gradle-build-action/src/caches.ts:73:1)
[19](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:19)
    at Object.<anonymous> (/home/runner/work/_actions/Wandalen/gradle-build-action/dist/webpack:/gradle-build-action/src/setup-gradle.ts:79:1)
[20](https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:20)
    at Generator.next (<anonymous>)

**Comment by bigdaz** [comment]
Thanks for the report @ben-manes: a few questions
-  Does this happen consistently for you, or is it sporadic?
-  Does this still occur if you apply the `gradle-build-action` directly, and not via [Wandalen/wretry.action@v1.0.20](https://github.com/ben-manes/caffeine/actions/runs/2459069519/workflow#L33-L40)?
- Does it still happen if you explicitly add `cache-read-only: false` to your action params?

For my own reference, here's a link to the failing run: https://github.com/ben-manes/caffeine/runs/6786982478?check_suite_focus=true#step:36:7

**Comment by ben-manes** [comment]
### [analysis.yml job](https://github.com/ben-manes/caffeine/actions/runs/2463720753)
 - variant: Removed `wretry.action`
 - result: no errors, and see job summaries

### [benchmarks.yml](https://github.com/ben-manes/caffeine/actions/runs/2463720759)
- variant: Added `cache-read-only` with `wretry.action`
- result: no errors, and see job summaries

### [examples.yml](https://github.com/ben-manes/caffeine/actions/runs/2463720762)
- variant: Added `cache-read-only`, removed `wretry.action`
- result: no errors, and see job summaries

### [build.yml](https://github.com/ben-manes/caffeine/actions/runs/2463720755)
 - variant: No change (with `wretry.action`, without `cache-read-only`)
 - result: `TypeError ` warnings, no  job summaries

---
This does seem to have started with the latest release when combined with `wretry.action`. When originally configuring that retry this warning had not occurred.

The `wretry.action` was added because I was seeing spurious network failures when downloading the jdk and gradle distribution. This started after splitting the `build.yml` job into parallel 117 jobs to reduce the runtime from 2.5hrs to ~30 minutes or less, where Github will run up to 20 jobs concurrently on the free tier. That could reasonably trigger some ddos protection rules and explain these network glitches. Adding the `wretry.action` seemed like a simple fix and removed the noise of these random failures. I am open to alternative suggestions.

Thanks @bigdaz!

**Comment by ben-manes** [comment]
Done. I will set this explicitly for now as I might prefer the old behavior since I use a long-lived dev branch and merge into the main branch once the changes are ready. I doubt many others use these two actions together and I agree with your preference to having it more explicitly in the action definition. Closing this in favor of https://github.com/Wandalen/wretry.action/issues/49

**Comment by bigdaz** [comment]
Thanks for the follow up. I really appreciate the testing and feedback.
