### ISSUE TITLE
./gradlew build is failing in my workflow

### ISSUE THREAD

**Issue by walksanatora** [gradle/gradle-build-action#706]
```
Error: Exception in thread "main" java.net.SocketException: Connection refused
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:202)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:[12](https://github.com/walksanatora/HexTweaks/actions/runs/4917101944/jobs/8781747883#step:5:13)63)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:[15](https://github.com/walksanatora/HexTweaks/actions/runs/4917101944/jobs/8781747883#step:5:16)89)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:[22](https://github.com/walksanatora/HexTweaks/actions/runs/4917101944/jobs/8781747883#step:5:23)4)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:87)
	at org.gradle.wrapper.Download.download(Download.java:67)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```
my workflow yaml
```	
name: Run Gradle on commit
on: [push]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    
    - name: 'Upload Forge Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: forge
        path: forge/build/libs
    - name: "Upload Fabric Artifact"
      uses: actions/upload-artifact@v3
      with:
        name: fabric
        path: fabric/build/libs
```

**Comment by bigdaz** [comment]
Is this failure consistent? It looks like the Gradle wrapper (`./gradlew`) is starting up, but is failing to download the full Gradle binaries.

**Comment by walksanatora** [comment]
I was able to fix it I think (checks the repo)
it was just a thing that happened a few times in a row so i decided to make a issue
